apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: hpe
  replicas: 3
  template:
    metadata:
      labels:
        app: hpe
    spec:
      containers:
      - image: smlinux/app:v1
        name: nodejs
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: hpe
  ports:
  - port: 80
    targetPort: 8080

