apiVersion: v1
kind: Pod
metadata:
  name: dynamic-web
spec:
  containers:

  - image: smlinux/cowsay-web
    name: web-generator
    volumeMounts:
    - name: html
      mountPath: /webdata

  - image: nginx:1.14
    name: web-server
    ports:
    - containerPort: 80
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
      readOnly: true

  volumes:
  - name: html
    emptyDir: {}
