apiVersion: apps/v1
kind: Deployment
metadata:
  name: stressful
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stress
  template:
    metadata:
      labels:
        app: stress
    spec:
      containers:
      - image: smlinux/vish-stress
        name: stress-container
