apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
         - name: MYSQL_ROOT_PASSWORD
           value: pass
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: dbdata
          mountPath: /var/lib/mysql
      volumes:
      - name: dbdata
        hostPath:
          path: /mysqldb
