apiVersion: v1
kind: Pod
metadata:
  name: fortune-cm-volume
spec:
  volumes:
  - name: html
    emptyDir: {}

  - name: config
    configMap:
      name: fortune

  containers:
  - image: smlinux/fortune:env
    env:
    - name: INTERVAL
      valueFrom:
        configMapKeyRef:
          name: fortune
          key: sleep-interval
    name: html-generator
    volumeMounts:
    - name: html
      mountPath: /var/htdocs

  - image: nginx:alpine
    name: web-server
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
      readOnly: true

    - name: config
      mountPath: /etc/nginx/conf.d
      readOnly: true
    ports:
    - containerPort: 80
