apiVersion: v1
kind: Pod
metadata:
  name: fortune-cm-volume2-secret
spec:
  containers:
  - image: smlinux/fortune:env
    name: html-generator
    env:
    - name: INTERVAL
      valueFrom:
        configMapKeyRef:
          name: fortune
          key: sleep-interval
    volumeMounts:
    - name: html
      mountPath: /var/htdocs

  - image: nginx:alpine
    name: web-server
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
      readOnly: true

    - name: config
      mountPath: /etc/nginx/conf.d
      readOnly: true

    - name: certs
      mountPath: /etc/nginx/certs/
      readOnly: true
    ports:
    - containerPort: 80
    - containerPort: 443

  volumes:
  - name: html
    emptyDir: {}

  - name: config
    configMap:
      name: fortune
      items:
      - key: my-nginx-config.conf
        path: https.conf

  - name: certs
    secret:
      secretName: fortune-https

