apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-daemonset
spec:
  selector:
    matchLabels:
      app: web
      version: "1.14"

  template:
    metadata:
      labels:
        app: nginx
        version: "1.14"
    spec:
      containers:
        - name: nginx
          image: nginx:1.14
